package explorviz.plugin.attributes;

public interface IPluginKeys {
	public static String WARNING_ANOMALY = "WARNING_ANOMALY";
	public static String ERROR_ANOMALY = "ERROR_ANOMALY";

	public static String TIMESTAMP_TO_RESPONSE_TIME = "TIMESTAMP_TO_RESPONSE_TIME";
	public static String TIMESTAMP_TO_PREDICTED_RESPONSE_TIME = "TIMESTAMP_TO_PREDICTED_RESPONSE_TIME";
	public static String TIMESTAMP_TO_ANOMALY_SCORE = "TIMESTAMP_TO_ANOMALY_SCORE";

	public static String ROOTCAUSE_RGB_INDICATOR = "ROOTCAUSE_RGB_INDICATOR";
	public static String ROOTCAUSE_APPLICATION_PROBABILITY = "ROOTCAUSE_APPLICATION_PROBABILITY";

	public static String CAPMAN_CPU_UTIL_HISTORY = "CAPMAN_CPU_UTIL_HISTORY";

	public static String CAPMAN_STATE = "CAPMAN_STATE";

	public static String CAPMAN_NEW_PLAN_ID = "CAPMAN_NEW_PLAN_ID";
	public static String CAPMAN_WARNING_TEXT = "CAPMAN_WARNING_TEXT";
	public static String CAPMAN_COUNTERMEASURE_TEXT = "CAPMAN_COUNTERMEASURE_TEXT";
	public static String CAPMAN_CONSEQUENCE_TEXT = "CAPMAN_CONSEQUENCE_TEXT";

	public static String CAPMAN_EXECUTION_STATE = "CAPMAN_EXECUTION_STATE";
}
